core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('sweat/<int:pk>', views.sweat_details, name='sweat'),
    path('sweat/like/<int:pk>', views.like, name='like'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('sweat/<int:pk>', views.sweat_details, name='sweat'),
    path('sweat/like/<int:pk>', views.like, name='like'),
]

sweater/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('tinymce/', include('tinymce.urls')),
]

core/models.py
from django.db import models
from tinymce import models as tiny_models


class Sweat(models.Model):
    title = models.CharField(max_length=5000)
    text = tiny_models.HTMLField()
    like = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'...{self.title}  |  {self.text[:15]}'


class About(models.Model):
    text = tiny_models.HTMLField()
    """
     the latest object of this model will be showed in the template,
     so every time creating a new one will be the last update.
    """
    last_update = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'...{self.last_update}  |  {self.text[:15]}'


class Footer(models.Model):
    title = models.CharField(max_length=100)
    text = tiny_models.HTMLField()
    last_update = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'...{self.title}  |  {self.text[:15]}'

core/views.py
from django.shortcuts import render, get_object_or_404
from .models import Sweat, About
from django.core.paginator import Paginator
from django.http.response import HttpResponse, JsonResponse


def index(request) -> HttpResponse:
    if request.session.get('likes') is None:
        request.session['likes'] = {}
    objects_list = Sweat.objects.order_by("-created_at")
    paginator = Paginator(objects_list, 3)
    page_num = request.GET.get('page')
    sweats = paginator.get_page(page_num)
    return render(request, 'core/index.html', {'sweats': sweats})


def sweat_details(request, pk) -> HttpResponse:
    sweat = get_object_or_404(Sweat, id=pk)
    return render(request, 'core/sweat.html', {'sweat': sweat})


def about(request) -> HttpResponse:
    about = About.objects.last()
    if about != None:
        pre_about = About.objects.filter(id=about.id - 1)
        pre_about.delete()
    return render(request, 'core/about.html', {'about': about})


def like(request, pk) -> JsonResponse:
    is_liked = request.session['likes'].get(f'sweat_number{pk}', False)
    sweat = Sweat.objects.get(id=pk)
    if is_liked:
        sweat.like -= 1
        sweat.save()
        request.session['likes'][f'sweat_number{pk}'] = False
        return JsonResponse({'response': 'unliked'})
    else:
        sweat.like += 1
        sweat.save()
        request.session['likes'][f'sweat_number{pk}'] = True
        return JsonResponse({'response': 'liked'})

home/views.py
from django.shortcuts import render, get_object_or_404
from .models import Sweat, About
from django.core.paginator import Paginator
from django.http.response import HttpResponse, JsonResponse


def home(request) -> HttpResponse:
    if request.session.get('likes') is None:
        request.session['likes'] = {}
    objects_list = Sweat.objects.order_by("-created_at")
    paginator = Paginator(objects_list, 3)
    page_num = request.GET.get('page')
    sweats = paginator.get_page(page_num)
    return render(request, 'home/home.html', {'sweats': sweats})


def sweat_details(request, pk) -> HttpResponse:
    sweat = get_object_or_404(Sweat, id=pk)
    return render(request, 'home/sweat.html', {'sweat': sweat})


def about(request) -> HttpResponse:
    about = About.objects.last()
    if about != None:
        pre_about = About.objects.filter(id=about.id - 1)
        pre_about.delete()
    return render(request, 'home/about.html', {'about': about})


def like(request, pk) -> JsonResponse:
    is_liked = request.session['likes'].get(f'sweat_number{pk}', False)
    sweat = Sweat.objects.get(id=pk)
    if is_liked:
        sweat.like -= 1
        sweat.save()
        request.session['likes'][f'sweat_number{pk}'] = False
        return JsonResponse({'response': 'unliked'})
    else:
        sweat.like += 1
        sweat.save()
        request.session['likes'][f'sweat_number{pk}'] = True
        return JsonResponse({'response': 'liked'})

core/templates/core/about.html
{% extends 'base.html' %}
{% load jalali_tags %}
{% block title %} About | درباره {% endblock %}

{% block header %} درباره {% endblock %}
{% block content %}
<div class="text">
{% if about %}
    <div class="about">
        <p>{{ about.text|safe }}</p>
    </div>
    <div class="last-update">
        <p>:آخرین بروزرسانی در</p>
        <small>{{ about.last_update|to_jalali:'%Y/%m/%d - %H:%M:%S' }}</small>
    </div>
{% endif %}
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'base.html' %}
{% load jalali_tags %}
{% block title %} Sweater | سوییتر {% endblock %}

{% block header %} سوییت ها {% endblock %}
{% block content %}
    {% if sweats != None %}
        {% for sweat in sweats %}
            <div class="sweat-card">
                <div class="box-element">
                    <h3>{{ sweat.title }}</h3>
                    <hr>
                    <br>
                    <p>{{ sweat.text|safe|truncatewords:30 }}</p><a style="font-size: 16pt" href="{% url 'core:sweat' sweat.id %}">...بیشتر</a>
                    <div class="end-sweat">
                        <i style="color: black" class="fa fa-heart"></i><span id="count"> {{ sweat.like }} </span>
                        <br>
                        <small>{{ sweat.created_at|to_jalali:'%Y/%m/%d - %H:%M:%S' }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
            <div class="text text-center">

                {% if sweats.has_other_pages %}
                    <nav aria-label="...">
                        <ul class="pagination justify-content-center">
                            {% if sweats.has_previous %}
                                <li class=" page-item">
                                    <a class="page-link" href="?page={{ sweats.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">قبلی</a>
                                </li>
                            {% else %}
                                <li class="page-item  disabled">
                                    <a class="page-link" href="#">قبلی</a>
                                </li>
                            {% endif %}
                            {% for i in sweats.paginator.page_range %}

                                {% if sweats.number == i %}
                                    <li class="page-item active ">
                                        <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
                                    </li>
                                {% endif %}

                            {% endfor %}
                            {% if sweats.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ sweats.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">بعدی</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                <a class="page-link" href="#">بعدی</a>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
    {% else %}
        <div class="container">
            <div class="text text-center">
                <h1>< no sweats yet ></h1>
            </div>
        </div>
    {% endif %}
{% endblock %}

core/templates/core/sweat.html
{% extends 'base.html' %}
{% load jalali_tags %}
{% load filters %}

{% if sweats != None %}
    {% block title %} Sweater | {{ sweat.title }} {% endblock %}
    {% block header %} <br> {% endblock %}
    {% block content %}
        <div class="sweat-card">
            <div class="box-element">
                <h3>{{ sweat.title }}</h3>
                <hr>
                <br>
                <p>{{ sweat.text|safe }}</p>
                <div class="end-sweat">
                    <a onclick="like({{ sweat.id }});"><i id="like" class="{{ request.session.likes|get_class:sweat.id }}"></i></a> <span id="count"> {{ sweat.like }} </span>
                    <br>
                    <small>{{ sweat.created_at|to_jalali:'%Y/%m/%d - %H:%M:%S' }}</small>
                </div>
            </div>
        </div>
    {% endblock %}
{% endif %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load jalali_tags %}
{% block title %} Sweater | سوییتر {% endblock %}

{% block header %} سوییت ها {% endblock %}
{% block content %}
    {% if sweats != None %}
        {% for sweat in sweats %}
            <div class="sweat-card">
                <div class="box-element">
                    <h3>{{ sweat.title }}</h3>
                    <hr>
                    <br>
                    <p>{{ sweat.text|safe|truncatewords:30 }}</p><a style="font-size: 16pt" href="{% url 'home:sweat' sweat.id %}">...بیشتر</a>
                    <div class="end-sweat">
                        <i style="color: black" class="fa fa-heart"></i><span id="count"> {{ sweat.like }} </span>
                        <br>
                        <small>{{ sweat.created_at|to_jalali:'%Y/%m/%d - %H:%M:%S' }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
            <div class="text text-center">

                {% if sweats.has_other_pages %}
                    <nav aria-label="...">
                        <ul class="pagination justify-content-center">
                            {% if sweats.has_previous %}
                                <li class=" page-item">
                                    <a class="page-link" href="?page={{ sweats.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">قبلی</a>
                                </li>
                            {% else %}
                                <li class="page-item  disabled">
                                    <a class="page-link" href="#">قبلی</a>
                                </li>
                            {% endif %}
                            {% for i in sweats.paginator.page_range %}

                                {% if sweats.number == i %}
                                    <li class="page-item active ">
                                        <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
                                    </li>
                                {% endif %}

                            {% endfor %}
                            {% if sweats.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ sweats.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">بعدی</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                <a class="page-link" href="#">بعدی</a>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
    {% else %}
        <div class="container">
            <div class="text text-center">
                <h1>< no sweats yet ></h1>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- styles -->
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'styles/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'styles/font-awesome.min.css' %}">
    <!-- fonts -->
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.eot' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.svg' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.ttf' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.woff' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.woff2' %}">
    <link rel="stylesheet" href="{% static 'fonts/FontAwesome.otf' %}">
    <!-- scripts -->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <title>{% block title %} {% endblock %}</title>
</head>
<body>

<!-- sidebar -->
{% include 'sidebar.html' %}

<!-- content -->
<div class="container sweat-align">
<h1 class="display-3">{% block header %} {% endblock %}</h1>
    {% block content %}

    {% endblock %}
</div>

<!-- footer -->
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load jalali_tags %}
<div id="footer" class="container sweat-algin">
    <hr id="footer-line">
    <div class="text-sm-end">
        <h1 class="display-5">{{ footer.title }}</h1>
        <br>
        <p>{{ footer.text|safe }}</p>
        <div class="last-update">
        <p>:آخرین بروزرسانی در</p>
        <small>{{ footer.last_update|to_jalali:'%Y/%m/%d - %H:%M:%S' }}</small>
    </div>
    </div>
</div>

templates/sidebar.html
<div class="sidebar">
    <a href="{% url 'core:index' %}">خانه</a>
    <a href="{% url 'core:about' %}">درباره</a>
    <a href="https://mortezashoeibi.github.io/donate.html">حمایت</a>
</div>